# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeDZxM0ZxEiTYEykJT83-RJnF6NZ3v7Q
"""

pip install streamlit pandas plotly scikit-learn

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestClassifier

# -----------------------------------------------------------------------------
# CONFIGURAÇÃO DA PÁGINA
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Passos Mágicos - Dashboard Analítico",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Estilo visual customizado
st.markdown("""
    <style>
    .main-title {
        color: #1E3A8A;
        font-size: 2.2rem;
        font-weight: bold;
        margin-bottom: 0px;
    }
    .subtitle {
        color: #4B5563;
        font-size: 1.1rem;
        margin-bottom: 20px;
    }
    .stMetric {
        background-color: #F3F4F6;
        padding: 15px;
        border-radius: 10px;
    }
    </style>
""", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# CABEÇALHO
# -----------------------------------------------------------------------------
st.markdown('<p class="main-title">🎓 Associação Passos Mágicos — Impacto & Predição</p>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Análise Longitudinal do Desenvolvimento Educacional (2022–2024)</p>', unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# DADOS FICTÍCIOS / SIMULADOS COM BASE NOS RESULTADOS DO MODELO
# (Substitua pela leitura do seu CSV consolidado se preferir)
# -----------------------------------------------------------------------------
@st.cache_data
def load_data():
    # Estrutura consolidada do IAN
    df_ian = pd.DataFrame({
        'Ano': [2022, 2022, 2022, 2022, 2023, 2023, 2023, 2023, 2024, 2024, 2024, 2024],
        'Nivel': ['Adequado', 'Defasagem Leve', 'Defasagem Moderada', 'Defasagem Severa'] * 3,
        'Percentual': [30.1, 47.6, 19.0, 3.3, 48.2, 41.1, 9.8, 0.9, 53.8, 38.1, 7.8, 0.3]
    })

    # Estrutura consolidada de Disciplinas
    df_notas = pd.DataFrame({
        'Ano': [2022, 2023, 2024],
        'IDA': [6.09, 6.66, 6.35],
        'Português': [6.32, 6.82, 6.18],
        'Matemática': [5.81, 6.41, 6.23],
        'Inglês': [5.88, 6.20, 6.60]
    })

    return df_ian, df_notas

df_ian, df_notas = load_data()

# -----------------------------------------------------------------------------
# ABAS DA APLICAÇÃO
# -----------------------------------------------------------------------------
tab1, tab2, tab3 = st.tabs(["📊 Visão Geral & Evolução", "🎯 Engajamento & Ponto de Virada", "🔮 Simulador Preditivo"])

# =============================================================================
# ABA 1: VISÃO GERAL
# =============================================================================
with tab1:
    st.subheader("Evolução dos Indicadores Educacionais")

    # KPI Highlights
    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Alunos em Nível Adequado (2024)", "53,8%", "+23,7% vs 2022")
    col2.metric("Erradicação Defasagem Severa", "0,3%", "-3,0% vs 2022")
    col3.metric("Média Nota de Inglês (2024)", "6.60", "+0.72 vs 2022")
    col4.metric("Média Engajamento (IEG)", "8.25", "+0.45 vs 2022")

    st.markdown("---")

    c1, c2 = st.columns(2)

    with c1:
        st.markdown("#### Evolução do Nível de Defasagem (IAN)")
        fig_ian = px.bar(
            df_ian,
            x='Ano',
            y='Percentual',
            color='Nivel',
            barmode='stack',
            color_discrete_sequence=px.colors.qualitative.Set2,
            text_auto=True
        )
        fig_ian.update_layout(yaxis_title="Percentual (%)", legend_title="Nível IAN")
        st.plotly_chart(fig_ian, use_container_width=True)

    with c2:
        st.markdown("#### Evolução Média por Disciplina (2022–2024)")
        fig_notas = go.Figure()
        fig_notas.add_trace(go.Scatter(x=df_notas['Ano'], y=df_notas['Português'], mode='lines+markers', name='Português'))
        fig_notas.add_trace(go.Scatter(x=df_notas['Ano'], y=df_notas['Matemática'], mode='lines+markers', name='Matemática'))
        fig_notas.add_trace(go.Scatter(x=df_notas['Ano'], y=df_notas['Inglês'], mode='lines+markers', name='Inglês', line=dict(dash='dash')))
        fig_notas.update_layout(yaxis_title="Nota Média", xaxis=dict(dtick=1))
        st.plotly_chart(fig_notas, use_container_width=True)

# =============================================================================
# ABA 2: ENGAJAMENTO & PONTO DE VIRADA
# =============================================================================
with tab2:
    st.subheader("O Engajamento (IEG) como Catalisador do Sucesso")

    col_a, col_b = st.columns([1, 1])

    with col_a:
        st.markdown("#### Comparativo: Atingiu o Ponto de Virada?")
        pv_data = pd.DataFrame({
            'Status': ['Não Atingiu PV', 'Atingiu PV'],
            'Engajamento (IEG)': [7.72, 9.01],
            'Desempenho (IDA)': [5.82, 7.87]
        })
        fig_pv = px.bar(
            pv_data,
            x='Status',
            y=['Engajamento (IEG)', 'Desempenho (IDA)'],
            barmode='group',
            text_auto='.2f',
            color_discrete_sequence=['#3B82F6', '#10B981']
        )
        fig_pv.update_layout(yaxis_title="Pontuação Média")
        st.plotly_chart(fig_pv, use_container_width=True)

    with col_b:
        st.info("""
        💡 **Insighs Principais do Engajamento:**
        * **Diferença Expressiva:** Alunos que atingem o Ponto de Virada (IPV) apresentam nota de engajamento média de **9,01**, contra **7,72** dos que não atingiram.
        * **Ganho de Rendimento:** O engajamento alto se reflete diretamente em **+2,05 pontos na média do IDA**.
        * **Correlação Forte:** $\text{IEG} \times \text{IDA} = 0.54$ e $\text{IEG} \times \text{IPV} = 0.56$.
        """)

# =============================================================================
# ABA 3: SIMULADOR PREDITIVO
# =============================================================================
with tab3:
    st.subheader("🔮 Simulador de Propensão ao Ponto de Virada")
    st.write("Insira os indicadores do aluno para estimar a probabilidade de atingimento do Ponto de Virada.")

    col_in1, col_in2, col_in3 = st.columns(3)

    with col_in1:
        ieg_sim = st.slider("Indicador de Engajamento (IEG)", 0.0, 10.0, 8.5, 0.1)
        ian_sim = st.selectbox("Nível IAN (Defasagem)", ["Adequado (0)", "Defasagem Leve (-1)", "Defasagem Moderada (-2)", "Defasagem Severa (-3)"])

    with col_in2:
        nota_mat = st.slider("Nota de Matemática", 0.0, 10.0, 6.5, 0.1)
        nota_por = st.slider("Nota de Português", 0.0, 10.0, 7.0, 0.1)

    with col_in3:
        fase_sim = st.selectbox("Fase do Aluno", [f"Fase {i}" for i in range(1, 9)])
        ips_sim = st.slider("Indicador Psicossocial (IPS)", 0.0, 10.0, 7.5, 0.1)

    # Regra Lógica Simulada para o Modelo
    # (Representa a propensão estimada com base nos coeficientes)
    base_score = (ieg_sim * 0.4) + (nota_mat * 0.25) + (nota_por * 0.25) + (ips_sim * 0.1)
    if "Adequado" in ian_sim:
        base_score += 1.0
    elif "Severa" in ian_sim:
        base_score -= 1.5

    probabilidade = min(max((base_score - 4.5) / 5.5, 0.0), 1.0) * 100

    st.markdown("---")
    st.markdown("### Resultado da Predição")

    col_res1, col_res2 = st.columns([1, 2])

    with col_res1:
        st.metric("Probabilidade de Ponto de Virada", f"{probabilidade:.1f}%")

    with col_res2:
        if probabilidade >= 70:
            st.success("🌟 **Alta Propensão!** O aluno apresenta excelente engajamento e métricas consistentes para atingir o Ponto de Virada.")
        elif probabilidade >= 40:
            st.warning("⚠️ **Atenção Média:** O aluno possui potencial, mas precisa de estímulo no engajamento (IEG) e reforço nas matérias base.")
        else:
            st.error("🚨 **Risco de Defasagem / Baixa Propensão:** Recomenda-se acompanhamento psicossocial imediato e plano de tutoramento individualizado.")

